trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: e2e_in_container
  displayName: Playwright in container
  container: mcr.microsoft.com/playwright:v1.48.2-jammy

  steps:
  - checkout: self
    fetchDepth: 1

  - script: |
      node -v
      npm -v
    displayName: Show Node/npm

  - script: |
      npm ci
      # Browsers are already in this image; this is optional but harmless:
      npx playwright install --with-deps
      npm run test:all
    displayName: Run Playwright tests

  # Sanity: always list where reports would be
  - script: |
      echo "Listing reports/junit:"
      ls -la reports/junit || true
      echo "Listing reports/html:"
      ls -la reports/html || true
      echo "Listing defaults (in case reporters were overridden):"
      ls -la junit-results.xml || true
      ls -la playwright-report || true
    displayName: List potential report locations
    condition: always()

  - task: PublishTestResults@2
    displayName: Publish JUnit
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'reports/junit/**/*.xml'
      testRunTitle: 'Playwright (container job)'

  - publish: reports/html
    artifact: PlaywrightHtmlReport
    condition: always()

  - script: |
      SUMMARY="$(Build.SourcesDirectory)/summary.md"
      {
        echo "# Containerized Playwright Run"
        echo ""
        echo "HTML report: **PlaywrightHtmlReport** (Artifacts)."
        echo "If empty, check the 'List potential report locations' step."
      } > "$SUMMARY"
      echo "##vso[task.uploadsummary]$SUMMARY"
    displayName: Attach summary
    condition: always()
