trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: e2e_in_container
  displayName: Playwright in container
  container: mcr.microsoft.com/playwright:v1.56.1-jammy

  variables:
    # Important: tells Playwright to use preinstalled browsers in the image
    PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

  steps:
  - checkout: self
    fetchDepth: 1

  - script: |
      node -v
      npm -v
    displayName: Show Node/npm

  - script: |
      echo "Installing project dependencies..."
      npm ci
      echo "Running Playwright tests..."
      npm run test:all
    displayName: Run Playwright tests

  - script: |
      echo "Listing reports/junit:"
      ls -la reports/junit || true
      echo "Listing reports/html:"
      ls -la reports/html || true
      echo "Listing defaults (in case reporters were overridden):"
      ls -la junit-results.xml || true
      ls -la playwright-report || true
    displayName: List potential report locations
    condition: always()

  - task: PublishTestResults@2
    displayName: Publish JUnit
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'reports/junit/**/*.xml'
      testRunTitle: 'Playwright (container job)'

  - publish: reports/html
    artifact: PlaywrightHtmlReport
    condition: always()
