trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: playwright_parallel
  displayName: Playwright Parallel Shards
  container: mcr.microsoft.com/playwright:v1.56.1-jammy

  strategy:
    matrix:
      shard1:
        SHARD_INDEX: 1
        SHARD_TOTAL: 4
      shard2:
        SHARD_INDEX: 2
        SHARD_TOTAL: 4
      shard3:
        SHARD_INDEX: 3
        SHARD_TOTAL: 4
      shard4:
        SHARD_INDEX: 4
        SHARD_TOTAL: 4

    variables:
    PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

  steps:
  - checkout: self
    fetchDepth: 1

  - script: |
      npm ci
      echo "Running shard $(SHARD_INDEX)/$(SHARD_TOTAL)"
      npx playwright test --shard=$(SHARD_INDEX)/$(SHARD_TOTAL)
    displayName: Run Playwright Shard
    continueOnError: true

  - task: PublishTestResults@2
    displayName: Publish JUnit for shard $(SHARD_INDEX)
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'reports/junit/**/*.xml'
      testRunTitle: "Playwright Shard $(SHARD_INDEX)"

  - publish: reports/html
    artifact: PlaywrightHtmlReport-$(SHARD_INDEX)
    condition: always()
